### ISSUE TITLE
Несколько хотелок

### ISSUE THREAD

**Issue by my-instantcms** [filinov/neomessenger-icms2.x#1]
Здравствуйте.
Загрузите пожалуйста последнюю версию неомессенджера сюда, что бы мы могли сделать Pull requests

Хотелки по коду:
Файл \system\controllers\neomessenger\hooks\before_print_head.php строку 51 и 52 заменить на

```
if(isset($this->options['is_favicon_count']) && $this->options['is_favicon_count']){
    $template->addControllerJS('libs/favico');
}
if(isset($this->options['is_title_count']) && $this->options['is_title_count']){
    $template->addControllerJS('libs/animatetitle');
}
```

Файл \templates\default\controllers\neomessenger\js\neomessenger.js строку 31 заменить на
`this.favicon     = nm.options.is_favicon_count ? this.initFavicon() : false;`

строку 97 заменить на
`var $msgButton = $('a[href="/messages"], a[href^="/messages/write/"]');`

строку 374 заменить на

```
if (app.options.is_title_count) {
    $.animateTitle('clear');
}
```

**Comment by filinov** [comment]
В ближайшее время постараюсь

**Comment by filinov** [comment]
репозиторий обновлен
